name: NWN nwsync
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: nwn_production
    steps:
      - name: Pull hak repository
        run: cd ~/mintarn-haks && git pull    
        
      - name: Pack mintarn.hak with nasher
        run: cd ~/mintarn-haks && docker run --rm --user 1019:1019 -v ${PWD}:/nasher kaikas/nasher:nwn_production pack hak --default
        
      - name: Copy hak to live server
        run: cd ~/mintarn-haks && cp mintarn.hak ~/nwn/server/hak/mintarn.hak
        
      - name: Pack mintarn.tlk with nasher
        run: cd ~/mintarn-haks && docker run --rm --user 1019:1019 -v ${PWD}:/nasher kaikas/nasher:nwn_production pack tlk --default
      
      - name: Copy tlk file
        run: cd ~/mintarn-haks && cp mintarn.tlk ~/nwn/server/tlk/mintarn.tlk

      - name: Pull portrait repository
        run: cd ~/mintarn-portraits && git pull    
        
      - name: Pack portraits.hak with nasher
        run: cd ~/mintarn-portraits && docker run --rm --user 1019:1019 -v ${PWD}:/nasher kaikas/nasher:nwn_production pack hak --default

      - name: Copy potrait hak file
        run: cd ~/mintarn-portraits && cp portraits.hak ~/nwn/server/hak/portraits.hak
        
      - name: Run nwsync
        run: cd ~/nwn/ && nwsync/nwsync_write --description="Mintarn Development" website/nwsync/ server/modules/Mintarn.mod
        
      - name: Restart live server
        run: docker-compose -f ~/nwn/docker-compose.yml restart
  build_dev:
    needs: build
    runs-on: nwn_develop
    steps:
      - name: Pull hak repository
        run: cd ~/mintarn-haks && git pull    
        
      - name: Pack mintarn.hak with nasher
        run: cd ~/mintarn-haks && docker run --rm --user 1017:1017 -v ${PWD}:/nasher kaikas/nasher:nwn_develop pack hak --default
        
      - name: Copy hak to dev server
        run: cd ~/mintarn-haks && cp mintarn.hak ~/nwn_dev/server/hak/mintarn.hak
      
      - name: Pack mintarn.tlk with nasher
        run: cd ~/mintarn-haks && docker run --rm --user 1017:1017 -v ${PWD}:/nasher kaikas/nasher:nwn_production pack tlk --default --target=tlk
      
      - name: Copy tlk file
        run: cd ~/mintarn-haks && cp mintarn.tlk ~/nwn_dev/server/tlk/mintarn.tlk

      - name: Pull portrait repository
        run: cd ~/mintarn-portraits && git pull    
        
      - name: Pack portraits.hak with nasher
        run: cd ~/mintarn-portraits && docker run --rm --user 1019:1019 -v ${PWD}:/nasher kaikas/nasher:nwn_production pack hak --default

      - name: Copy potrait hak file
        run: cd ~/mintarn-portraits && cp portraits.hak ~/nwn/server/hak/portraits.hak
        
        
      - name: Restart dev server
        run: docker-compose -f ~/nwn_dev/docker-compose.yml restart
