# This is a basic workflow to help you get started with Actions

name: NWN Devserver

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: nwn_develop

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs nasher to pack the module
      - name: Run nasher pack to build Mintarn.mod
        run: docker run --rm -v ${PWD}:/nasher nwntools/nasher:latest pack

      # Copy module to correct folder
      - name: Copy module to server
        run: cp Mintarn.mod ~/nwn_dev/server/modules/
        
      # Restart nwn server
      - name: Restart the dev server
        run: docker-compse -f ~/nwn_dev/docker-compose.yml restart
